### ISSUE TITLE
Microsoft.JSInterop.JSException: Could not find 'TimeGhost.IndexedDbManager.openDb' ('TimeGhost' was undefined)

### ISSUE THREAD

**Issue by drma-tech** [wtulloch/Blazor.IndexedDB#37]
I know you already have an open ticket in this regard, but I just wanted to reinforce it.

I have version 1.5 of the component and I am using the blazor wasm (net 5) and js is still not found. And I have already configured the following reference:
`<script src="_content/TG.Blazor.IndexedDB/indexedDb.Blazor.js"></script>`

![image](https://user-images.githubusercontent.com/12803050/105088390-95c29780-5a7a-11eb-90d1-29dfd63c1120.png)

```
blazor.webassembly.js:1 fail: VerusDate.Web.Pages.Profile.Index[0]
      ProcessException
Microsoft.JSInterop.JSException: Could not find 'TimeGhost.IndexedDbManager.openDb' ('TimeGhost' was undefined).
Error: Could not find 'TimeGhost.IndexedDbManager.openDb' ('TimeGhost' was undefined).
    at https://localhost:5001/_framework/blazor.webassembly.js:1:1287
    at Array.forEach (<anonymous>)
    at e.findFunction (https://localhost:5001/_framework/blazor.webassembly.js:1:1247)
    at b (https://localhost:5001/_framework/blazor.webassembly.js:1:2989)
    at https://localhost:5001/_framework/blazor.webassembly.js:1:3935
    at new Promise (<anonymous>)
    at Object.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.webassembly.js:1:3908)
    at Object.w [as invokeJSFromDotNet] (https://localhost:5001/_framework/blazor.webassembly.js:1:64218)
    at _mono_wasm_invoke_js_blazor (https://localhost:5001/_framework/dotnet.5.0.0.js:1:190800)
    at do_icall (https://localhost:5001/_framework/dotnet.wasm:wasm-function[10595]:0x194e46)
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__15`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at TG.Blazor.IndexedDB.IndexedDBManager.<CallJavascript>d__28`1[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at TG.Blazor.IndexedDB.IndexedDBManager.OpenDb()
   at TG.Blazor.IndexedDB.IndexedDBManager.EnsureDbOpen()
   at TG.Blazor.IndexedDB.IndexedDBManager.<GetRecordById>d__21`2[[System.String, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[VerusDate.Shared.Model.ProfileModel, VerusDate.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
```

**Comment by SteveWark** [comment]
I'm encountering the same issue.  I have a "standard" Blazor WASM application that I added Blazor.IndexDB to and added openDB etc to the "Counter" page, I have buttons that Open the DB and that add 100 records to the DB.  This app is blazor wasm (net 5) and it works with no issues.

On another project, which is part of a solution that has an API project as well I've duplicated the code and added the open DB etc to the Counter page again, however, this time, when I first click the button to open the DB I get the error and it asks for  Reload, opening Developer Tools I see the error 'TimeGhost' was undefined.  If I click the Reload and then try the OpenDB button all works and I can add the 100 records.

The new WASM app in the solution I have added JWT tokens (6.8.0) , Blazored.Toast (3.1.2), BlazorInoputFile (0.2.0) and BlazoredLocalStorage (3.0.0).

**Comment by nasisakk** [comment]
@drma-dev Did you solve this issue?  I was unable to find any commit for it...

**Comment by drma-tech** [comment]
i dont use it anymore

**Comment by jeanpoulin** [comment]
FIXED: I had the same issue and unable to find answer on any post but but try & error I conclude that as I was playing with multiple version of my app maybe my browser was mixed-up but in any case when I did CTRL-F5 to clear cache it fixed my problem

**Comment by nasisakk** [comment]
Unfortunately, ctrl-f5 didn't fix it in my scenario--that was one of the first things I tried...

**Comment by Ibanez1408** [comment]
I am using .net6 blazor wasm. At first I had an issue with the JSInterop when using Reshisru.Blazor.IndexedDb,Framework. Then I installed this package found here https://github.com/wtulloch/Blazor.IndexedDB I got the issue 'TimeGhost' was undefined so I just did what @jeanpoulin have done and it fixed the issue.
